config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: "pages#home"
  # get "/dashboard", to: "users#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # the user can see their challenges on their challenges page
  resources :challenges, only: [:index, :show ]
  get "/calendar", to: "user_challenges#index"
  # add tracker page
  get "/dashboard", to: "user_challenges#dashboard"

  get "/dashboard/:id", to: "challenges#select"

  resources :user_challenges, only: [:update]
  resources :user_answers, only: [:index]
  resources :questions, only: [:show] do
    resources :user_answers, only: [:create]
  end
  resources :challenges, only: [:index] do
    resources :user_challenges, only: [:create]
  end
end

app/views/pages/home.html.erb
<%# <div class="banner" style="background-position: center; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=image_path"139606_s.jpg"%>

<div id="home-banner">
    <% if user_signed_in? && current_user.user_answers.exists?%>
      <h2>Welcome back to your Plastic-free Journey!</h2>
    <% else %>
      <h2>Start Your Plastic-free Journey!</h2>
    <% end %>
  <p>miraihabit helps you reduce your plastic footprint by completing daily challenges.
    <br>
    Reduce your plastic consumption and choose new sustainable alternatives!</p>
  <div class="col-6 mx-auto">
    <% if user_signed_in? && current_user.user_answers.exists?%>
      <%= link_to "Check your Dashboard", dashboard_path, id: "btn-home-cta" %>
    <% else %>
      <%= link_to "Take an assessment", question_path(@first_question), id: "btn-home-cta" %>
    <% end %>

  </div>
</div>
</div>
<div id="home-container">
  <div id="carouselExampleDark" class="carousel carousel-dark slide d-flex justify-content-center">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">
        <%= image_tag "carousel_1.png" ,class:"d-block w-100 custom-carousel"%>
        <div class="carousel-caption d-none d-md-block">
          <h3 class="">Step 1</h3>
          <h4 class="">Take a quick online assessment to get a starting score</h4>
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <%= image_tag "carousel_2.png" ,class:"d-block w-100 custom-carousel"%>
        <div class="carousel-caption d-none d-md-block">
          <h3 class="">Step 2</h3>
          <h4 class="">Choose & complete your daily challenges with new sustainable alternatives</h4>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag "carousel_3.png" ,class:"d-block w-100 custom-carousel"%>
        <div class="carousel-caption d-none d-md-block">
          <h3 class="">Step 3</h3>
          <h4 class="">Track and Reduce your plastic footprint to save your sea turtle from plastic waste!</h4>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>