config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: "pages#home"
  # get "/dashboard", to: "users#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # the user can see their challenges on their challenges page
  resources :challenges, only: [:index, :show ]
  get "/calendar", to: "user_challenges#index"
  # add tracker page
  get "/dashboard", to: "user_challenges#dashboard"

  get "/dashboard/:id", to: "challenges#select"

  resources :user_challenges, only: [:update]
  resources :user_answers, only: [:index]
  resources :questions, only: [:show] do
    resources :user_answers, only: [:create]
  end
  resources :challenges, only: [:index] do
    resources :user_challenges, only: [:create]
  end
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :answer, optional: true
  has_many :user_challenges, dependent: :destroy
  has_many :users, through: :user_challenges
  has_one_attached :photo

  validates :difficulty, :name, :description_what, :description_why, :max_score, :duration, presence: true
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def index
    sql = <<~SQL
      CURRENT_DATE >= DATE(user_challenges.created_at) + challenges.duration + 1 -- INACTIVE
    SQL

    challenges_never_done = Challenge.all - current_user.challenges
    inactive_challenges = current_user.challenges.joins(:user_challenges).where(sql).distinct
    # We reload the records in SQL (so that we can use .where):
    @challenges = policy_scope(Challenge).where(id: challenges_never_done + inactive_challenges)

    if params.dig(:challenge, :category).present?
      @challenges = @challenges.where(category: params.dig(:challenge, :category).downcase)
    end

    if params.dig(:challenge, :difficulty).present?
      @challenges = @challenges.where(difficulty: params.dig(:challenge, :difficulty).to_i)
    end

    # raise
    @user_challenge = UserChallenge.new
  end

  def show
    @challenge = Challenge.find(params[:id])
    @user_challenge = UserChallenge.new
    authorize @challenge
  end

  def select
    @challenge = Challenge.find(params[:id])
    authorize @challenge
    respond_to do |format|
      # format.html # Follow regular flow of Rails
      format.text { render partial: "user_challenges/details", locals: {challenge: @challenge}, formats: [:html] }
    end
    # raise
  end
end

app/views/challenges/_card.html.erb
<div class="challenge-card-small justify-content-between">

  <div class="d-flex justify-content-start" >
    <%= image_tag "#{challenge.category}.png", class: "d-flex align-items-center justify-content-center" %>
    <div class="row justify-content-start">
      <%# <div class ="col-4 d-flex flex-column"> %>
      <%# <div class="challenge-card-small-infos" style="justify-content-between text-align: center"> %>
      <%# </div> %>
      <%# </div> %>
      <div class ="col-8 width-450">
        <h3><b><%= challenge.name %></b></h3>
        <% if challenge.difficulty == 1 %>
          <h5>Environmental Impact: <i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i><i class="fa-regular fa-star"></i></h5>
        <% elsif challenge.difficulty == 2 %>
          <h5>Environmental Impact: <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i></h5>
        <% elsif challenge.difficulty == 3 %>
          <h5>Environmental Impact: <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></h5>
        <% end %>
        <h5><%= challenge.max_score / 7 %>  <i class="fa-solid fa-leaf"></i></h5>
        <% if  challenge.duration == 1%>
          <h5><b>Duration: </b><%= challenge.duration %> day</h5>
          <!--<h5><%= challenge.duration %> day</h5>-->
        <% else %>
          <h5><b>Duration:  </b><%= challenge.duration %> days</h5>
          <!--<h5><%= challenge.duration %> days</h5>-->
        <% end %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-end">
    <div class="me-3">
      <%= link_to challenge_path(challenge), class: "btn btn-secondary w-100 mb-2 text-white" do %>

        <i class="fa-solid fa-info"></i><b>  Info</b>
      <% end %>
      <%# unless current_user.challenges.include?(challenge) %>
      <% user_challenge = UserChallenge.where(user: current_user, challenge: challenge).first %>
      <%= render "user_challenges/user_challenge_create_form", challenge: challenge, user_challenge: @user_challenge %>
    </div>
  </div>
</div>

app/views/challenges/_card_nonplus.html.erb
<div class="challenge-card-small justify-content-between">
  <%= image_tag "#{challenge.category}.png"%>
  <div class="row justify-content-between">
    <%# <div class ="col-4 d-flex flex-column"> %>
    <%# <div class="challenge-card-small-infos" style="justify-content-between text-align: center"> %>
    <%# </div> %>
    <%# </div> %>
    <div class ="col-8 width-250">
      <h3><%= challenge.name %></h3>
      <% if challenge.difficulty == 1 %>
        <h4>Environmental Impact: <i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i><i class="fa-regular fa-star"></i></h4>
      <% elsif challenge.difficulty == 2 %>
        <h4>Environmental Impact: <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i></h4>
      <% elsif challenge.difficulty == 3 %>
        <h4>Environmental Impact: <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></h4>
      <% end %>
      <h5><%= challenge.max_score / 7%>  <i class="fa-solid fa-leaf"></i></h5>
    </div>
  </div>
  <div class="me-3">
    <%#= link_to dashboard_path do %>
      <%# <i class="fa-solid fa-plus fs-4"></i>  Add to your dashboard %>
      <%# end %>
      <%= link_to challenge_path(challenge), class: "btn btn-danger challenge-card-show-detail-text w-100 mb-2 px-5 text-white" do %>
        <i class="fa-solid fa-info"></i><b>  Info</b>
      <% end %>
      <%# unless current_user.challenges.include?(challenge) %>
    </div>
  </div>

app/views/challenges/index.html.erb
<!--
<div class="banner" style="background-position: center; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%=image_path"139606_s.jpg"%>);">
</div>
-->
<div class="container" style="padding-top: 20px">
  <div class="container" style="text-align: center">
    <h1>Browse All Challenges</h1>
    <p>Filter through all of our challenges, and choose which ones you'd like to try to start your plastic-free journey!</p>
  </div>
  <hr>
  <div class="d-flex justify-content-center">
    <%= simple_form_for :challenge, url: challenges_path, method: :get, data: { controller: 'autosave' } do |f| %>
      <div class="d-flex mt-3">
        <div class="me-5">
          <h5>Category</h5>
          <%= f.input :category,
            as: :radio_buttons,
            input_html: { class: "category-selector" },
            item_wrapper_class: 'category-item',
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'},
            collection: ["Food", "Hygiene", "Cleaning"],
            legend_html: { class: "d-none"}
             %>
        </div>
        <div>
          <h5>Environmental Impact</h5>
          <%= f.input :difficulty,
            as: :radio_buttons,
            collection_wrapper_tag: 'div',
            collection_wrapper_class: 'category-wrapper',
            item_wrapper_class: 'category-item',
            input_html: {class: 'category-selector'},
            collection: [["★☆☆", 1], ["★★☆", 2], ["★★★", 3]],
            label: false
             %>
        </div>
        <div class="d-flex justify-content-center align-items-center font-weight-bold">
          <button class="btn btn-danger btn-lg rounded-pill text-white" style="margin-left: 30px;" type="submit"><b>Search</b></button>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class= "challenge-card-flex container">
    <% @challenges.each do |challenge| %>
      <%# unless current_user.challenges.include?(challenge) %>
      <%= render 'challenges/card', challenge: challenge %>
      <%# end %>
    <% end %>
</div>

app/views/challenges/show.html.erb
<div class="container">
  <div class="challenge-show-backbtn">
    <%= link_to '<< Back', challenges_path, class: "btn btn-outline-info mt-2 text-decoration-none" %>
  </div>
  <div class="challenge-card-show">
    <div class="d-flex justify-content-center align-items-center">
      <h1 class="m-3">
        <b><%= @challenge.name %></b>
      </h1>
      <% unless current_user.challenges.include?(@challenge) %>
        <%= render "user_challenges/user_challenge_create_form", challenge: @challenge, user_challenge: @user_challenge %>
      <% end %>
    </div>
    <hr>
    <div class="d-flex justify-content-center">
      <%= image_tag "#{@challenge.category}.png", class: "icon-category"%>
      <div class="m-1">
        <% if @challenge.difficulty == 1 %>
          <h4><b>Environmental Impact: </b><i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i><i class="fa-regular fa-star"></i></h4>
        <% elsif @challenge.difficulty == 2 %>
          <h4><b>Environmental Impact: </b><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-regular fa-star"></i></h4>
        <% elsif @challenge.difficulty == 3 %>
          <h4><b>Environmental Impact: </b><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i></h4>
        <% end %>
        <div class="d-flex m-1 justify-content-center">
          <% if  @challenge.duration == 1%>
            <h4><b>Duration: </b></h4>
            <h4><%= @challenge.duration %> day</h4>
          <% else %>
            <h4><b>Duration:  </b></h4>
            <h4><%= @challenge.duration %> days</h4>
          <% end %>
        </div>
        <h4><%= @challenge.max_score / 7%> <i class="fa-solid fa-leaf"></i></h4>
      </div>
    </div>
    <hr>
    <div class="d-flex justify-content-between align-items-center">
      <div class="m-3" >
        <div class="mt-3">
          <h3><b>Did you know?</b></h3>
          <p  class="mt-3"><%= @challenge.description_what %></p>
        </div>
        <div class="mt-3">
          <h3><b>What you can do</b></h3>
          <p  class="mt-3"><%= @challenge.description_why %></p>
        </div>
      </div>
      <div class="m-3">
        <%= cl_image_tag @challenge.photo.key, width: "300", class:"img_border" %>
      </div>
    </div>
  </div>
</div>